# Generated by Django 5.2.2 on 2025-06-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeseries', '0002_timeseries_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseries',
            name='date_column',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='timeseries',
            name='numeric_column',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
