# Generated by Django 5.2 on 2025-05-19 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timeseries', '0002_timeseries_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timeseries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_runs', to='timeseries.timeseries')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForecastMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='forecasting.forecastrun')),
            ],
        ),
    ]
