# Generated by Django 5.2.1 on 2025-06-03 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0001_initial'),
        ('timeseries', '0002_timeseries_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastrun',
            name='timeseries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecast_runs', to='timeseries.timeseries'),
        ),
    ]
