# Generated by Django 5.2.2 on 2025-06-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0002_alter_forecastrun_timeseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastrun',
            name='script_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
