# Generated by Django 5.2.2 on 2025-06-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0003_forecastrun_script_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastrun',
            name='csv_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
